--------------------------------------------------------
--  File created - Thursday-July-07-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence FC_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FLASHCARD"."FC_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 25 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table FLASHCARD
--------------------------------------------------------

  CREATE TABLE "FLASHCARD"."FLASHCARD" 
   (	"FC_ID" NUMBER(*,0), 
	"FC_QUESTION" VARCHAR2(4000 BYTE), 
	"FC_ANSWER" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FLASHCARD.FLASHCARD
SET DEFINE OFF;
Insert into FLASHCARD.FLASHCARD (FC_ID,FC_QUESTION,FC_ANSWER) values (1,'Is this java?','Java it is');
Insert into FLASHCARD.FLASHCARD (FC_ID,FC_QUESTION,FC_ANSWER) values (2,'What is Java?','Its coffee...were you expecting something else?');
Insert into FLASHCARD.FLASHCARD (FC_ID,FC_QUESTION,FC_ANSWER) values (3,'Why do Java Developers need glasses?','Because they can''t C#');
Insert into FLASHCARD.FLASHCARD (FC_ID,FC_QUESTION,FC_ANSWER) values (4,'If you rebuilt Hibernate what would you call it?','Napster');
Insert into FLASHCARD.FLASHCARD (FC_ID,FC_QUESTION,FC_ANSWER) values (5,'ok','sure');
Insert into FLASHCARD.FLASHCARD (FC_ID,FC_QUESTION,FC_ANSWER) values (20,'why do you?','123');
--------------------------------------------------------
--  Constraints for Table FLASHCARD
--------------------------------------------------------

  ALTER TABLE "FLASHCARD"."FLASHCARD" ADD UNIQUE ("FC_QUESTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLASHCARD"."FLASHCARD" ADD PRIMARY KEY ("FC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FLASHCARD"."FLASHCARD" MODIFY ("FC_ANSWER" NOT NULL ENABLE);
  ALTER TABLE "FLASHCARD"."FLASHCARD" MODIFY ("FC_QUESTION" NOT NULL ENABLE);
  ALTER TABLE "FLASHCARD"."FLASHCARD" MODIFY ("FC_ID" NOT NULL ENABLE);
